### ISSUE TITLE
The code doesn't run

### ISSUE THREAD

**Issue by liudi-didi** [DonaldHwang/DCASE2021-SELD#1]
Can this code run in WIN?I have an error running on WIN.（IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed）can you give me a hand，thanks

**Comment by huangdaolang** [comment]
Hi, the code is quite messy, can you provide me with more details so that I can help you with your problem? Thanks!

**Comment by RicardoMLi** [comment]
Do u have a WeChat，if u have，could u please add me WeChat，my WeChat is LDZZ1103.Thanks，bro，love U！

**Comment by liudi-didi** [comment]
> Hi, the code is quite messy, can you provide me with more details so that I can help you with your problem? Thanks!

For convenience, I reduced fod_dev to 100 and foa_eval to 50. Is this the reason why the code doesn't run?  After seld_mian runs, I will display the error (num_samples should be a positive integer value, but got num_samples=0), I will print the data, and it will show 0, there is a problem with the data loading, but I don't know exactly where it happened.
